# Generated by Django 4.2.8 on 2023-12-09 22:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_popular', models.BooleanField(max_length=255)),
                ('is_trending', models.BooleanField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Too Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3)),
                ('number_of_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Too Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3)),
                ('content', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_File', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'wmv', 'flv', 'webm', 'mpeg', 'mpg'])])),
                ('duration', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(related_name='coureses', to='courses.instructor'),
        ),
    ]
