# Generated by Django 4.2.8 on 2023-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_trending',
            field=models.BooleanField(),
        ),
    ]
